import unittest
import numpy as np
import sys

# Ensure the main engine is imported correctly
try:
    import Assignment4_Q1_StructuralAnalysisEngine as eng
except ImportError:
    print("\n[CRITICAL ERROR] Could not import the main engine file.")
    print("Please ensure 'Assignment4_Q1_StructuralAnalysisEngine.py' is in the same directory as this test file.")
    sys.exit(1)


class QA_StructuralTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        print("=" * 80)
        print("   STRUCTURAL ENGINE QUALITY ASSURANCE (QA) TEST SUITE")
        print("   Testing Modules: Thermal Loading & Support Settlements")
        print("=" * 80)

    def evaluate_and_report(self, test_name, param_name, expected, actual, tolerance=1e-5, feedback=""):
        """ Custom feedback mechanism that explains the test evaluation process. """
        diff = abs(expected - actual)
        print(f"\n[EVALUATING] {test_name}")
        print(f"  -> Parameter Under Test : {param_name}")
        print(f"  -> Expected Value       : {expected:.4f}")
        print(f"  -> Actual Engine Value  : {actual:.4f}")
        print(f"  -> Tolerance Limit      : {tolerance:.1e}")

        if diff <= tolerance:
            print(f"  [✓] STATUS: PASSED (Difference: {diff:.2e} is within limits)")
        else:
            print(f"  [X] STATUS: FAILED (Difference: {diff:.2e} exceeds limits!)")
            print(f"  [!] DIAGNOSTIC FEEDBACK: {feedback}")
            self.fail(f"{test_name} failed. Check console for diagnostic feedback.")

    # =========================================================================
    # UNIT TESTS (Testing individual functions/methods in isolation)
    # =========================================================================

    def test_unit_thermal_fef_formulation(self):
        """ UNIT TEST 1: Verifies the Fixed-End Forces (FEF) for Thermal Actions """
        # Setup: Isolated Element Properties
        E, A, I = 200e6, 0.05, 0.0004
        alpha, h = 1.2e-5, 0.3
        dT_avg, dT_grad = 10.0, 5.0  # +10C uniform, +5C gradient

        node_1 = eng.Node(1, 0, 0)
        node_2 = eng.Node(2, 5, 0)  # L = 5m

        element = eng.Element(1, node_1, node_2, E, A, I,
                              eng.ElementType.FRAME, eng.Release.NONE,
                              alpha, h, dT_avg, dT_grad)

        _, fef = element._get_raw_stiffness_and_fef()

        # Theoretical Hand Calculation
        # 1. Axial FEF (P = E * A * alpha * dT_avg)
        expected_P = E * A * alpha * dT_avg  # 200e6 * 0.05 * 1.2e-5 * 10 = 1200 kN
        # 2. Moment FEF (M = E * I * alpha * dT_grad / h)
        expected_M = (E * I * alpha * dT_grad) / h  # 200e6 * 0.0004 * 1.2e-5 * 5 / 0.3 = 16 kNm

        self.evaluate_and_report(
            "Unit Test 1.A: Thermal Axial Force (Uniform dT)",
            "P_fef (Start Node)", expected_P, fef[0],
            feedback="Axial force formulation is incorrect. Check P = E * A * alpha * dT_avg."
        )

        self.evaluate_and_report(
            "Unit Test 1.B: Thermal Moment (Gradient dT)",
            "M_fef (Start Node)", expected_M, fef[2],
            feedback="Moment formulation is incorrect. Check M = (E * I * alpha * dT_grad) / h."
        )

    def test_unit_settlement_equivalent_force(self):
        """ UNIT TEST 2: Verifies equivalent nodal forces generated by settlements """
        # Setup: A spring-like bar to easily track stiffness
        E, A, L = 1000, 1.0, 1.0  # k = EA/L = 1000 kN/m
        node_1 = eng.Node(1, 0, 0)
        node_2 = eng.Node(2, L, 0)
        node_2.settlements[0] = 0.05  # Node 2 settles 5cm to the right

        element = eng.Element(1, node_1, node_2, E, A, I=1e-12, elem_type=eng.ElementType.TRUSS)

        k_local, _ = element.get_condensed_matrices()
        d_settlement = np.array([0.0, 0.0, 0.0, 0.05, 0.0, 0.0])  # Node 1:0, Node 2: Ux=0.05

        # Engine calculation: F_settlement = [K] * {D_settlement}
        f_settlement = k_local @ d_settlement

        # Expected: Node 1 should feel a pulling force of 50 kN (1000 * 0.05) to the right (+50)
        # But equivalent nodal force goes to RHS as negative, so internally it's -50.
        expected_force_on_node1 = k_local[0, 3] * 0.05  # (-1000) * 0.05 = -50

        self.evaluate_and_report(
            "Unit Test 2: Support Settlement Force Generation",
            "Equivalent Force on Node 1 (Ux)", expected_force_on_node1, f_settlement[0],
            feedback="Partitioning matrix multiplication for settlement is wrong. Check K_global @ D_settlement."
        )

    # =========================================================================
    # INTEGRATION TESTS (Testing multiple systems working together)
    # =========================================================================

    def test_integration_pure_thermal_restraint(self):
        """ INTEGRATION TEST 1: Full system solve for a heated, fully fixed beam. """
        model = eng.Structure()
        # Both nodes are fully fixed
        n1 = eng.Node(1, 0, 0, restraints=[True, True, True])
        n2 = eng.Node(2, 5, 0, restraints=[True, True, True])
        model.add_node(n1)
        model.add_node(n2)

        # Heated by 50 degrees
        el = eng.Element(1, n1, n2, E=200e6, A=0.01, I=0.0004, dT_avg=50.0)
        model.add_element(el)

        model.solve()  # Execute Global Assembly and Solver

        # Validation 1: Displacement must be exactly 0
        self.evaluate_and_report(
            "Integration Test 1.A: Pure Thermal (Displacement Check)",
            "Node 2 Displacement (Ux)", 0.0, n2.displacements[0],
            feedback="Nodes moved despite being fully fixed! Check DOF assignment logic."
        )

        # Validation 2: Internal Force must equal E*A*alpha*dT = 200e6*0.01*1.2e-5*50 = 1200 kN
        self.evaluate_and_report(
            "Integration Test 1.B: Pure Thermal (Internal Force Check)",
            "Element 1 Axial Force (Start)", 1200.0, el.local_forces[0],
            feedback="Global assembly failed to back-calculate thermal internal forces on locked nodes."
        )

    def test_integration_differential_settlement(self):
        """ INTEGRATION TEST 2: Full system solve for a fixed beam with a settling support. """
        model = eng.Structure()

        # Node 2 settles downwards by 0.01m (1cm)
        n1 = eng.Node(1, 0, 0, restraints=[True, True, True])
        n2 = eng.Node(2, 5, 0, restraints=[True, True, True], settlements=[0.0, -0.01, 0.0])
        model.add_node(n1)
        model.add_node(n2)

        E, I, L, delta = 200e6, 0.0004, 5.0, -0.01
        el = eng.Element(1, n1, n2, E=E, A=0.05, I=I)
        model.add_element(el)

        model.solve()

        # Theoretical Moments caused by differential settlement: M = 6*E*I*delta / L^2
        expected_moment = (6 * E * I * abs(delta)) / (L ** 2)  # 6 * 200e6 * 0.0004 * 0.01 / 25 = 192 kNm
        # Theoretical Shear: V = 12*E*I*delta / L^3 = 76.8 kN
        expected_shear = (12 * E * I * abs(delta)) / (L ** 3)

        self.evaluate_and_report(
            "Integration Test 2.A: Differential Settlement (Fixed-End Moment)",
            "Moment Mz at Node 1", expected_moment, abs(el.local_forces[2]),
            feedback="The global solver did not correctly transfer settlement equivalent loads to the force vector."
        )

        self.evaluate_and_report(
            "Integration Test 2.B: Differential Settlement (Induced Shear)",
            "Shear Vy at Node 1", expected_shear, abs(el.local_forces[1]),
            feedback="Shear equilibrium failed during settlement analysis. Check global stiffness assembly."
        )


if __name__ == '__main__':
    # Run the tests with minimal verbosity, since our custom feedback mechanism handles the detailed printing
    unittest.main(verbosity=1, exit=False)
    print("\n" + "=" * 80)
    print("   END OF QUALITY ASSURANCE TESTS")
    print("=" * 80 + "\n")